version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: mikhmon-bluekarma
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8001:8001"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 103.137.140.6  # Untuk Windows/Mac
      DB_PORT: 3306
      DB_DATABASE: hotspot
      DB_USERNAME: root
      DB_PASSWORD: password
    command: php artisan serve --host=0.0.0.0 --port=8001
